# The Docker image that will be used to build your app
image: node:20
# Functions that should be executed before the build script is run
before_script:
  - npm ci
pages:
  script:
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
    - npm run build:github  # Construye el proyecto (genera la carpeta `dist`)
    - mv dist public # Renombra `dist` a `public` para GitLab Pages
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
